# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(847, 451)
        MainWindow.setMinimumSize(QtCore.QSize(850, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 822, 393))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.analyzerHorizontalLayout = QtWidgets.QHBoxLayout()
        self.analyzerHorizontalLayout.setObjectName("analyzerHorizontalLayout")
        self.graphWidget = PlotWidget(self.verticalLayoutWidget)
        self.graphWidget.setMinimumSize(QtCore.QSize(400, 300))
        self.graphWidget.setObjectName("graphWidget")
        self.analyzerHorizontalLayout.addWidget(self.graphWidget)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.typeVerticalLayout = QtWidgets.QVBoxLayout()
        self.typeVerticalLayout.setObjectName("typeVerticalLayout")
        self.inputHorizontalLayout = QtWidgets.QHBoxLayout()
        self.inputHorizontalLayout.setContentsMargins(10, 20, 10, 10)
        self.inputHorizontalLayout.setSpacing(10)
        self.inputHorizontalLayout.setObjectName("inputHorizontalLayout")
        self.addressLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.addressLineEdit.setFont(font)
        self.addressLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.inputHorizontalLayout.addWidget(self.addressLineEdit)
        self.addressButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.addressButton.setFont(font)
        self.addressButton.setObjectName("addressButton")
        self.inputHorizontalLayout.addWidget(self.addressButton)
        self.typeVerticalLayout.addLayout(self.inputHorizontalLayout)
        self.verticalLayout_2.addLayout(self.typeVerticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.parametersHorizontalLayout = QtWidgets.QHBoxLayout()
        self.parametersHorizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.parametersHorizontalLayout.setContentsMargins(10, -1, 10, 0)
        self.parametersHorizontalLayout.setSpacing(20)
        self.parametersHorizontalLayout.setObjectName("parametersHorizontalLayout")
        self.frequencyVerticalLayout = QtWidgets.QVBoxLayout()
        self.frequencyVerticalLayout.setObjectName("frequencyVerticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.fstartLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fstartLabel.setObjectName("fstartLabel")
        self.gridLayout.addWidget(self.fstartLabel, 0, 0, 1, 1)
        self.fstepLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fstepLabel.setObjectName("fstepLabel")
        self.gridLayout.addWidget(self.fstepLabel, 2, 0, 1, 1)
        self.fstepLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fstepLineEdit.setObjectName("fstepLineEdit")
        self.gridLayout.addWidget(self.fstepLineEdit, 2, 2, 1, 1)
        self.fbwLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fbwLineEdit.setObjectName("fbwLineEdit")
        self.gridLayout.addWidget(self.fbwLineEdit, 3, 2, 1, 1)
        self.fstopLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fstopLineEdit.setObjectName("fstopLineEdit")
        self.gridLayout.addWidget(self.fstopLineEdit, 1, 2, 1, 1)
        self.fstopLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fstopLabel.setObjectName("fstopLabel")
        self.gridLayout.addWidget(self.fstopLabel, 1, 0, 1, 1)
        self.fstartLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.fstartLineEdit.setObjectName("fstartLineEdit")
        self.gridLayout.addWidget(self.fstartLineEdit, 0, 2, 1, 1)
        self.fsetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.fsetButton.setObjectName("fsetButton")
        self.gridLayout.addWidget(self.fsetButton, 3, 3, 1, 1)
        self.fbwLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fbwLabel.setObjectName("fbwLabel")
        self.gridLayout.addWidget(self.fbwLabel, 3, 0, 1, 1)
        self.frequencyVerticalLayout.addLayout(self.gridLayout)
        self.parametersHorizontalLayout.addLayout(self.frequencyVerticalLayout)
        self.refVerticalLayout = QtWidgets.QVBoxLayout()
        self.refVerticalLayout.setSpacing(0)
        self.refVerticalLayout.setObjectName("refVerticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dbLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.dbLabel.setObjectName("dbLabel")
        self.gridLayout_2.addWidget(self.dbLabel, 2, 0, 1, 1)
        self.refLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.refLabel.setObjectName("refLabel")
        self.gridLayout_2.addWidget(self.refLabel, 1, 0, 1, 1)
        self.refLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.refLineEdit.setObjectName("refLineEdit")
        self.gridLayout_2.addWidget(self.refLineEdit, 1, 1, 1, 1)
        self.dbLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.dbLineEdit.setObjectName("dbLineEdit")
        self.gridLayout_2.addWidget(self.dbLineEdit, 2, 1, 1, 1)
        self.refButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.refButton.setObjectName("refButton")
        self.gridLayout_2.addWidget(self.refButton, 1, 2, 1, 1)
        self.dbButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.dbButton.setObjectName("dbButton")
        self.gridLayout_2.addWidget(self.dbButton, 2, 2, 1, 1)
        self.singleCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.singleCheckBox.setObjectName("singleCheckBox")
        self.gridLayout_2.addWidget(self.singleCheckBox, 3, 1, 1, 1)
        self.continuousCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.continuousCheckBox.setObjectName("continuousCheckBox")
        self.gridLayout_2.addWidget(self.continuousCheckBox, 3, 2, 1, 1)
        self.triggerLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.triggerLabel.setObjectName("triggerLabel")
        self.gridLayout_2.addWidget(self.triggerLabel, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 3)
        self.refVerticalLayout.addLayout(self.gridLayout_2)
        self.parametersHorizontalLayout.addLayout(self.refVerticalLayout)
        self.verticalLayout_2.addLayout(self.parametersHorizontalLayout)
        self.analyzerHorizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.analyzerHorizontalLayout)
        self.generatorHorizontalLayout = QtWidgets.QHBoxLayout()
        self.generatorHorizontalLayout.setContentsMargins(-1, 9, -1, -1)
        self.generatorHorizontalLayout.setObjectName("generatorHorizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName("listWidget")
        self.generatorHorizontalLayout.addWidget(self.listWidget)
        self.verticalLayout.addLayout(self.generatorHorizontalLayout)
        # MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 847, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        # MainWindow.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MainWindow)
        # self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addressButton.setText(_translate("MainWindow", "CONNECT"))
        self.fstartLabel.setText(_translate("MainWindow", "f.start"))
        self.fstepLabel.setText(_translate("MainWindow", "f.step"))
        self.fstopLabel.setText(_translate("MainWindow", "f.stop"))
        self.fsetButton.setText(_translate("MainWindow", "SET"))
        self.fbwLabel.setText(_translate("MainWindow", "f.bw"))
        self.dbLabel.setText(_translate("MainWindow", "dB/div"))
        self.refLabel.setText(_translate("MainWindow", "Ref level"))
        self.refButton.setText(_translate("MainWindow", "SET"))
        self.dbButton.setText(_translate("MainWindow", "SET"))
        self.singleCheckBox.setText(_translate("MainWindow", "Single"))
        self.continuousCheckBox.setText(_translate("MainWindow", "Continuous"))
        self.triggerLabel.setText(_translate("MainWindow", "TRIGGER"))
        self.label.setText(_translate("MainWindow", "Parametry"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

